spring:
  rabbitmq:
    host: 192.168.37.131
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirms: true
    publisher-returns: true
    listener:
      direct:
        acknowledge-mode: manual
      type: direct  # 指定messageListerFactory类型的工厂


